objects/Navigation_Item__c.object
<CustomObject>
    <fields>
        <fullName>Filter_Criteria__c</fullName>
        <inlineHelpText>SOQL Filter Criteria. Use operators including =, !=, LIKE</inlineHelpText>
        <label>Filter Criteria</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Icon_Name__c</fullName>
        <label>Icon Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NavigationType__c</fullName>
        <label>NavigationType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>standard__namedPage</fullName>
                </value>
                <value>
                    <fullName>standard__navItemPage</fullName>
                </value>
                <value>
                    <fullName>standard__appPage</fullName>
                </value>
                <value>
                    <fullName>standard__recordPage</fullName>
                </value>
                <value>
                    <fullName>standard__objectPage</fullName>
                </value>
                <value>
                    <fullName>standard__recordRelationshipPage</fullName>
                </value>
                <value>
                    <fullName>standard__webPage</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>Object API Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PageName__c</fullName>
        <label>Page Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>LandingPage</fullName>
                    <default>true</default>
                    <label>LandingPage</label>
                </value>
                <value>
                    <fullName>BusinessApps</fullName>
                </value>
                <value>
                    <fullName>EPC</fullName>
                </value>
                <value>
                    <fullName>CPQ</fullName>
                </value>
                <value>
                    <fullName>OM</fullName>
                </value>
                <value>
                    <fullName>DocumentGeneration</fullName>
                </value>
                <value>
                    <fullName>DIgitalCommerce</fullName>
                </value>
                <value>
                    <fullName>Omnistudio</fullName>
                </value>
                <value>
                    <fullName>Page2</fullName>
                    <isActive>false</isActive>
                    <label>Page2</label>
                </value>
                <value>
                    <fullName>Page3</fullName>
                    <isActive>false</isActive>
                    <label>Page3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelatedEntityAPIName__c</fullName>
        <inlineHelpText>Use only if Navigation Type = &quot;standard__recordRelationshipPage&quot;</inlineHelpText>
        <label>Related Entity API Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Detail__c</fullName>
        <label>Section Detail</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Section_Heading__c</fullName>
        <label>Section Heading</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Target_App__c</fullName>
        <label>Target App</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_RecordId__c</fullName>
        <label>Target RecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Tab_Name__c</fullName>
        <label>Target Location</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Navigation Item</label>
    <nameField>
        <displayFormat>NI-{0000}</displayFormat>
        <label>Navigation Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navigation Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetItems.cls
public without sharing class GetItems {
    

    @AuraEnabled(cacheable = true)
    public static List<Navigation_Item__c>  getPageItems(String pageName){
        List<Navigation_Item__c> items = new List<Navigation_Item__c>();
        for(Navigation_Item__c item : [SELECT Id,Icon_Name__c, Section_Detail__c,Section_Heading__c,Target_App__c,RelatedEntityAPIName__c,Target_Tab_Name__c,NavigationType__c,Filter_Criteria__c,Target_RecordId__c, ObjectName__c
        FROM Navigation_Item__c WHERE isActive__c = true and PageName__c =:pageName order by Sequence_Number__c ]){
            if(item.Filter_Criteria__c != null){
                String recordId = getRecordIdBasedOnFilter(item.ObjectName__c,item.Filter_Criteria__c);
                if(recordId != null){
                    item.Target_RecordId__c = recordId;
                }
            }
            items.add(item);
        }
        return items;
    }

     private static String getRecordIdBasedOnFilter(String objectName, String filter){
        String soqlQuery = 'select Id,Name from ' + objectName + ' where ' + filter;
        try{
            List<Sobject> results = database.query(soqlQuery);
            return results[0].Id;
        }    
        catch(Exception e){
            return null;
        }
            
    }

}